### ISSUE TITLE
Fails to build with Ninja as CMake generator

### ISSUE THREAD

**Issue by JamiKettunen** [AyatanaIndicators/libayatana-common#60]
With the following Void Linux build template file`libayatana-common` fails to build via `xbps-src`:
<details>
  <summary>Click to show/hide the template</summary>
  
  ```bash
# Template file for 'libayatana-common'
pkgname=libayatana-common
version=0.9.7
revision=1
build_style=cmake
build_helper="gir"
configure_args="-DENABLE_LOMIRI_FEATURES=$(vopt_if lomiri ON OFF)"
hostmakedepends="pkg-config $(vopt_if vala 'vala') intltool ubports-cmake-extras"
makedepends="glib-devel $(vopt_if lomiri 'lomiri-url-dispatcher-devel') gobject-introspection"
checkdepends="gtest-devel"
short_desc="Common functions that two or more system indicator components share"
maintainer="Jami Kettunen <jami.kettunen@protonmail.com>"
license="GPL-3.0-only"
homepage="https://github.com/AyatanaIndicators/libayatana-common"
changelog="https://raw.githubusercontent.com/AyatanaIndicators/libayatana-common/main/ChangeLog"
distfiles="https://github.com/AyatanaIndicators/libayatana-common/archive/refs/tags/${version}.tar.gz"
checksum=4a17c7c80ca2c5641df4f4e326b4fe77a5ebbd700bfd1ac2ccefc29eec5118d1

build_options="vala lomiri"
desc_option_lomiri="Build with Lomiri-specific libraries, schemas and media"
build_options_default="vala lomiri"

if [ "$XBPS_CHECK_PKGS" ]; then
	configure_args+=" -DENABLE_TESTS=ON"
fi

libayatana-common-devel_package() {
	depends="${sourcepkg}>=${version}_${revision}"
	short_desc+=" - development files"
	pkg_install() {
		vmove usr/include
		vmove usr/lib/pkgconfig
		vmove usr/share/gir-1.0
		if [ "${build_option_vala}" ]; then
			vmove usr/share/vala
		fi
		vmove "usr/lib/*.so"
	}
}
  ```
</details>

The error (technically a warning) generated is:
```
CMake Error:
  Running

   '/usr/bin/ninja' '-C' '/builddir/libayatana-common-0.9.7/build' '-t' 'recompact'

  failed with:

   ninja: warning: phony target 'data/org.ayatana.common.gschema.xml' names itself as an input; ignoring [-w phonycycle=warn]

  ninja: error: build.ninja:357: multiple rules generate
  data/org.ayatana.common.gschema.xml [-w dupbuild=err]
```

I'm currently working around this by setting it back to the CMake default generator of `Unix Makefiles`:
```bash
make_cmd="make"
export CMAKE_GENERATOR="Unix Makefiles"
```

Package versions in build chroot:
```
[host] pkg-config-0.29.2_3: found (https://alpha.de.repo.voidlinux.org/current)
[host] vala-0.54.7_1: found (https://alpha.de.repo.voidlinux.org/current)
[host] intltool-0.51.0_6: found (https://alpha.de.repo.voidlinux.org/current)
[host] ubports-cmake-extras-1.7r286_1: found (/host/binpkgs/lomiri)
[host] cmake-3.22.2_1: found (https://alpha.de.repo.voidlinux.org/current)
[host] ninja-1.10.2_2: found (https://alpha.de.repo.voidlinux.org/current)
[host] gobject-introspection-1.70.0_1: found (https://alpha.de.repo.voidlinux.org/current)
[target] glib-devel-2.70.2_1: found (https://alpha.de.repo.voidlinux.org/current)
[target] lomiri-url-dispatcher-devel-0.1.1r758_1: found (/host/binpkgs/lomiri)
[target] gobject-introspection-1.70.0_1: found (https://alpha.de.repo.voidlinux.org/current)
```

**Comment by JamiKettunen** [comment]
It appears the same issue will be happening to all the indicators I'm package as well (if they build in a similar way to `ayatana-indicator-session`); I'll link them all to this issue if that's ok.

**Comment by sunweaver** [comment]
@JamiKettunen: I am not getting the exact problem here. We have build instructions and your ninja approach seems non-standard. Why are you using ninja?

If you feel we can improve the CMake rules in this (and the other) project(s), please file a pull request with your proposed changes. Thanks.

Without a pull request / patch, we cannot help you much here (as ninja is not what we use for build this). Please explain in depth. Thanks.

**Comment by kalj** [comment]
I am also seeing this. The point of cmake is that it abstract away the generator (e.g. GNU make, ninja, etc), so it is not a good sign that it only works with one of them. I agree with @ahesford that something is probably mildly wrong in the cmake logic.

I can try to help finding the error - but some clues to how the `data/org.ayatana.common.gschema.xml` is supposed to be generated would be helpful.

**Comment by JamiKettunen** [comment]
@kalj @mariogrip Previously mentioned to me that it's probably https://gitlab.com/ubports/development/core/cmake-extras/-/blob/5f56466d/src/GSettings/GSettingsConfig.cmake#L97 and that
> it should not depend on the output of `add_custom_command()`

There was a similar problem on `geonames` which he fixed with [this](https://gitlab.com/ubports/development/core/geonames/-/merge_requests/1/diffs?commit_id=992568064cc7e8bcb7e88e91e26f3cc7b2c71391) but I think it was dropped on that MR in favor of [that](https://gitlab.com/ubports/development/core/geonames/-/merge_requests/1/diffs?commit_id=bb10187d24f72ff5cdbe01ab11178bf098d72c6e). He also mentioned that
> it might also be in `intltool_merge_translations()`

https://gitlab.com/ubports/development/core/cmake-extras/-/blob/5f56466d/src/Intltool/IntltoolConfig.cmake#L368

**Comment by sunweaver** [comment]
@kalj: Can you please use those two geonames patches and apply something similar on top of libayatana-common and report back if that FTBFS of yours gets fixed with that?

**Comment by kalj** [comment]
Thanks for the response, but it seems that the problem has already been solved :) I was building 0.9.7, and when I tried out `main`, it no longer had the problem. I believe it was fixed in #61. So yeah, this can probably be closed.

**Comment by kalj** [comment]
Maybe all the other ayatana-indicator-* issues listed by @JamiKettunen have been fixed as well then?

**Comment by JamiKettunen** [comment]
Sounds promising! I've indeed only last tested with `libayatana-common` 0.9.7 previously, now there's 0.9.8 tagged which I'll take a look at later tonight :)

**Comment by JamiKettunen** [comment]
Yep can confirm no longer a problem on `libayatana-common` 0.9.8! I shall see if it's a problem on the other indicators I also observed the same problem on ^^
